---
- hosts: cache_flush
  gather_facts: false

  tasks:
    - name: Run container
      become: True
      command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} up -d"
      register: container
    - name: Check container status
      debug: msg={{ container }}
    - name: Get PHP Container ID
      become: True
      command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} ps -q php"
      register: container_id
    - debug: msg={{ container_id.stdout }}
    - command: "docker exec {{ container_id.stdout }} bin/magento cache:status"
    - command: "docker exec {{ container_id.stdout }} bin/magento cache:flush"
