---
 - hosts: staging_docker
   gather_facts: false
   become: true
   environment:
    PYTHONPATH: /root/.local/lib/python2.7/site-packages


   tasks:
    - name: Triming branch name
      shell: echo "{{ branch }}" | sed 's/.*origin1\///'
      register: branch_name
    - debug: msg={{ branch_name.stdout }}
    - name: pull from git
      git:
        repo: "{{ repository }}"
        dest: "{{ project_path }}"
        update: yes
        version: "{{ branch_name.stdout }}"
        force: yes
    - name: Enabling maintenance enable...
      include_role:
        name: roles/maintenance_enable
    - name: Running composer install
      include_role:
        name: roles/composer_install
    - name: Running setup upgrade
      include_role:
        name: roles/setup_upgrade
    - name: Running di-compile
      include_role:
        name: roles/setup_di_compile
    - name: Running static content deploy
      include_role:
        name: roles/static-content_deploy
    - name: Setting permissions
      include_role:
        name: roles/commands
    - name: Disabling maintenance mood
      include_role:
        name: roles/maintenance_disable
    - name: Restarting docker setup
      include_role:
       name: roles/docker_restart
      tags: restart
    - name: Reindex all 
      include_role:
       name: roles/reindex_all
      tags: reindex_all
    - name: Restart elasticsearch container
      include_role:
       name: roles/elasticsearch_restart
      tags: elasticsearch_restart
