---
- hosts: staging_docker
  gather_facts: false

  tasks:
    - include_vars: vars.yml
    - docker_service:
        project_src: "{{ project_path }}"
        build: no
        restarted: yes
      register: output
    - debug: msg={{ output }}
    - command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composeyaml }} ps -q php"
      register: container_id
    - debug: msg={{ container_id.stdout }}
    - command: "{{ item }}"
      with_items:
              - "{{ dep_cmd }}"
    - docker_service:
        project_src: "{{ project_path }}"
        build: no
        restarted: yes
