---
# tasks file for roles/prana-admin
    - command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} down"
      register: container_id
      tags: prana-admin-build
    - debug: msg={{ container_id.stdout }}
    - command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} up -d --build"
      register: container_id
      tags: prana-admin-build
    - debug: msg={{ container_id.stdout }}
