---
# tasks file for roles/setup_di_compile
    - name: Checking container status
      become: True
      command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} up -d"
    - command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} ps -q php"
      register: container_id
      tags: di_compile
    - command: "docker exec {{ container_id.stdout }} bin/magento setup:di:compile"
      register: setup_di_compile
      tags: di_compile
    - debug: msg={{ setup_di_compile }}
      tags: di_compile
