---
# tasks file for roles/setup_upgrade
#
    - name: Checking container status
      become: True
      command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} up -d"
    - command: bash -lc "cd {{ project_path }} && docker-compose -f {{ composefile }} ps -q php"
      register: container_id
    - command: "docker exec {{ container_id.stdout }} bin/magento setup:upgrade"
